//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileTransferWindowsService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAXPILT_LOG
    {
        public int ID { get; set; }
        public string XML_SOURCE { get; set; }
        public string XML_RESPONSE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    
        public virtual TRAXPILT_STATUS TRAXPILT_STATUS { get; set; }
    }
}
