//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileTransferWindowsService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAXPILT_SET
    {
        public int ID { get; set; }
        public Nullable<int> EX_TIME { get; set; }
        public System.DateTime LAST_EXECUTION_TIME { get; set; }
    }
}
