//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileTransferWindowsService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAXPILT_STATUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAXPILT_STATUS()
        {
            this.TRAXPILT_LOG = new HashSet<TRAXPILT_LOG>();
        }
    
        public int ID { get; set; }
        public int CODE { get; set; }
        public string NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAXPILT_LOG> TRAXPILT_LOG { get; set; }
    }
}
